[SCRUM-36 + 37] dolaczanie ucznia
Nepommuck/Software-Engineering-Frontend pull request #3
Opened 2024-05-26 17:14 UTC by flakboy

https://student-team-ea3gjw6z.atlassian.net/browse/SCRUM-37

2024-05-26 22:03 UTC, Nepommuck requested changes
Bardzo fajnie! Parę rzeczy prosiłbym o zmianę, zostawiłem też trochę sugestii, które możesz wykonać lub zignorować.

Czego nam na pewno brakuje, to autoformatera kodu. Myślę, że ogarnę w najbliższej przyszłości konfigurację Prettier'a, bo jak zaczniemy we dwójkę commitować do tego samego projektu, to widzę, że może być mega ciężko xd

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/model.ts
> +    name: string;
Dodaj `readonly` jeśli tylko jest taka możliwość

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/model.ts
> +export interface IStudent {
Sugestia: Personalnie nazwałbym to po prostu `Student`

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.html
> +    <form *ngIf="!isRegistered; else waiting_screen" #userForm="ngForm" class="register__form" (submit)="submitForm()">
W nowszych wersjach angulara dostępne są alternatywne wyrażenia if-else:
```  
  @if(!isRegistered) {
    <form #userForm="ngForm" class="register__form" (submit)="submitForm()">
      ...
    </form>
  } @else {
    <p>Oczekiwanie na rozpoczęcie sesji...</p>
  }
```

Moim zdaniem ten sposób jest bardziej czytelny, ale nie zmuszam jeśli wolisz `*ngIf`

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.css
> +.register__form {
Hmm kojarzę konwencję, żeby słowa w klasach CSS rozdzielać myślikiem, a więc `register-form`. Zmień, jeśli uważasz za słuszne

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.css
> +.register__button {
Ja bym personlanie użył po prostu klasy `register` oraz selektorów `div.register`, `button.register`, `input.register` itd.

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/app.component.html
>  <h1>Mobile app for the kids</h1>
1. Zmień proszę na napis po polsku
2. Strasznie brakuje jakiegokolwiek marginesu / paddingu

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/app.component.html
> +<router-outlet></router-outlet>
Minor: obecnie w angularze można używać pojedynczego selektora do komponentów, jeśli nie żadnego `<ng-content>` w środku, a więc mógłbyś to zmienić na `<router-outlet />`

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.spec.ts
> +describe('RegisterComponent', () => {
Te pliki `.spec.ts` można spokojnie usuwać po stworzeniu komponentu. Myślę, że nie będziemy używać tych testów

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.ts
> +    private router: Router,
Minor: dependency injection można też osiągnąć w taki sposób:

```
private router = inject(Router)
```

Dzięki temu nie trzeba korzystać w konstruktora

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.ts
> +import { LobbyEvent, LobbyEventStatus } from './model';
Minor: nieużywany import

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.html
> +            <input matInput name="name" [(ngModel)]="model.name" type="text" minlength="4" required class="register__input" placeholder="Jan Kowalski"/>
Hmm, czyli dlatego nie było `readonly`. Tak szczerze to nie podoba mi się to. Proponowałbym stworzyć osobną zmienną na `[(ngModel)]`, a instancje tego `IStudent` niech będą niemutowalne. Może być tworzona taka instancja np. dopiero przy submicie formularza

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.html
> +        <!-- <button [disabled]="!userForm.valid" (click)="submitForm()" mat-button class="register__button"> Dołącz </button> -->
Rozumiem, że warto to zostawić, bo jest tutaj użyte `submitForm()`. Jeśli zostawiasz zakomentowany kod, to zostaw też proszę komentarz dlaczego np.:
```
<!-- TODO Can be used as soon as (...) will be ready -->
```

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.service.ts
> +  constructor() { }
Pusty konstruktor jest równoważny jego brakowi. Możesz spokojnie skasować tę linię

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.service.ts
> +  ngOnDestroy() {
Wydaje mi się, że to będzie miało efekt tylko jeśli dodasz `implements OnDestroy` przy klasie

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.html
> +            <input matInput name="name" [(ngModel)]="model.name" type="text" minlength="4" required class="register__input" placeholder="Jan Kowalski"/>
Jeśli pojedynczy tag zajmuje tak dużo miejsca w ramach jednej linii, to proponuję pisać każdy jego argument w osobnym wierzu, a więc:
```
<input 
	matInput name="name" 
	[(ngModel)]="model.name" 
	type="text" 
	minlength="4" 
	required class="register__input" 
	placeholder="Jan Kowalski"
/>
```

2024-05-26 22:03 UTC, Nepommuck commented on IO-phone/src/index.html
>    <app-root></app-root>
Może być `<app-root />`

2024-05-27 06:09 UTC, flakboy commented on IO-phone/src/app/register/register.component.css
> +.register__form {
Ogólnie to ten podwójny underscore to jest kwestia używania metodyki BEM (czyli to nie jest "register form" a bardziej "form w module register"), natomiast w sumie to i tak chyba faktycznie bym odrobinę zmienił tą nazwę klasy. No i też w sumie się zastanawiam, czy stosowanie tej konwencji w Angularze ma wiele sensu, także poprawię

2024-05-27 06:10 UTC, flakboy commented on IO-phone/src/index.html
>    <app-root></app-root>
To jest w sumie i tak kod wygenerowany przez Angulara którego ja za bardzo nie modyfikowałem

2024-05-27 06:21 UTC, flakboy commented on IO-phone/src/app/register/register.component.ts
> +    private router: Router,
Czy powinienem w ten sposób injectować wszystkie serwisy i podobne zależności? I czy warto używać tego sposobu jeśli np. constructor nie byłby pusty?

2024-05-27 06:23 UTC, flakboy commented on IO-phone/src/app/register/register.component.html
> +        <!-- <button [disabled]="!userForm.valid" (click)="submitForm()" mat-button class="register__button"> Dołącz </button> -->
Właściwie to po prostu po sobie nie posprzątałem, bo nie wiedziałem czy będzie mi wystarczyć przypisanie submitForm do formularza, a nie przycisku. Natomiast wszystko wydaje się dobrze działać więc to usunę

2024-05-27 06:29 UTC, flakboy commented on IO-phone/src/app/register/register.component.html
> +            <input matInput name="name" [(ngModel)]="model.name" type="text" minlength="4" required class="register__input" placeholder="Jan Kowalski"/>
Tak właściwie, to ten interfejs wykorzystywany jest WYŁĄCZNIE jako model formularza, także może faktycznie warto by było zaznaczyć to jakoś w nazwie (czy proponujesz jakąś konwencję?).

2024-05-27 06:32 UTC, flakboy commented on IO-phone/src/app/register/register.service.ts
> +  ngOnDestroy() {
A jak to działa w przypadku OnInit? Czy powinienem też to dopisywać? Bo nie dopisywałem takiego interfejsu do komponentów, a jednak ngOnInit się wykonuje.

2024-05-27 07:03 UTC, flakboy commented on IO-phone/src/index.html
>    <app-root></app-root>
Update: w tym miejscu NIE MOŻE być `<app-root />`. Nie rozumiem dlaczego to działa w ten sposób, natomiast zamiana tego znacznika z kontenerowego na pojedynczy sprawia, że componenty z `@angular/material` mogą nie działać jak należy.

Przykład:
![obraz](https://github.com/Nepommuck/Software-Engineering-Frontend/assets/58552499/d33f9ca0-055a-405d-ade0-8fd7c7e39139)
(Uwaga: aby zobaczyć tą różnicę, nie wystarczy zmienić `index.html`. Trzeba też zrestartować `ng serve`.)


Nie potrafię powiedzieć, czy jest to bug Angularowy, czy problem wynikający z mojego kodu

2024-05-27 21:55 UTC, Nepommuck commented on IO-phone/src/index.html
>    <app-root></app-root>
Hmm rzeczywiście, bardzo ciekawe bugi powstają

Przepraszam w takim razie, wygląda na to, że ten `<app-root>` jest z jakiegoś powodu specjalny

2024-05-27 21:59 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.css
> +.register__form {
Bardzo ciekawe, nie słyszałem wcześniej o tej metodyce BEM. Myślę, że ma ona dużo sensu, więc jeśli tylko masz ochotę ją tutaj stosować, to śmiało!

2024-05-27 22:19 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.ts
> +export class RegisterComponent {
Dodaj proszę `implements OnInit`. Działa co prawda bez tego, ale IDE może wtedy podkreślać `ngOnInit()` jako nieużywaną metodę

2024-05-27 22:19 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.ts
> +    private router: Router,
Tak ogólnie to jest to kwestią gustu. `inject` pozwala na używanie wstrzykniętych dependencji jeszcze przed konstrukotrem, dzięki czemu mamy np.:

```
export class PollEditorComponent implements OnInit {
  private readonly unsavedPollService = inject(UnsavedPollService)
  // ...
  protected currentPoll = this.unsavedPollService.poll
  protected newPollName = this.unsavedPollService.poll.name
```
zamiast

```
export class PollEditorComponent implements OnInit {
  private readonly unsavedPollService = inject(UnsavedPollService)
  // ...
  protected currentPoll!: Poll
  protected newPollName!: string
  
  constructor(
    private unsavedPollService: UnsavedPollService,
  ) {
    this.currentPoll = unsavedPollService.poll
    this.newPollName = unsavedPollService.poll.name
  }
```
Pierwsza opcja jest wyraźnie lepsza, bo nie posiada `!:` - operatora, który wierzy, że programista ustawi jeszcze zmienną na coś innego, niż `undefined`, ale wcale tego nie sprawdza. Zaletą wstrzyknięcia przez konstruktor byłaby sytuacja, gdy danej dependencji nie potrzebujemy jako pole klasy, a jedynie do inicjalizacji czegoś w konstruktorze. Wtedy np. dla:
```
  constructor(
    unsavedPollService: UnsavedPollService,
  ) {
    this.currentPoll = unsavedPollService.poll
    this.newPollName = unsavedPollService.poll.name
  }
```
nie tworzylibyśmy pola `this.unsavedPollService`.

Jeśli nie wystąpił żaden z tych 2 przypadków, to wybór którego _dependency injection_ się używa jest jedynie kwestią gustu

2024-05-27 22:23 UTC, Nepommuck commented on IO-phone/src/app/register/register.component.html
> +            <input matInput name="name" [(ngModel)]="model.name" type="text" minlength="4" required class="register__input" placeholder="Jan Kowalski"/>
Hmm to wiele wyjaśnia. W takim razie może `RegstrationFormValue`? Ciężko mi powiedzieć, bo raczej nie widziałem takich zastosowań interfejsów, ale jeśli tylko Ci tak wygodnie, to spoko

2024-05-27 22:30 UTC, Nepommuck commented on IO-phone/src/app/register/register.service.ts
> +  ngOnDestroy() {
Hmm, być może faktycznie będzie to działać. Proponuję jednak dodawać to `implements OnDestroy` ze względu na podpowiedzi w IDE

2024-05-27 22:34 UTC, Nepommuck reviewed
Obczaj komentarze, które nie są jeszcze `respolved`, dokonaj zmian jeśli uznasz za konieczne i możesz już merge'ować

2024-05-27 22:44 UTC, Nepommuck approved these changes

2024-05-28 08:15 UTC, merged